[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -U pip setuptools wheel", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 wsgi:app"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"