providers = ["python"]

[phases.setup]
nixPkgs = ["pkgs.python311", "pkgs.libGL", "pkgs.glib", "pkgs.pkg-config"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --graceful-timeout 30 --threads 2 wsgi:app"

# Release phase for Railway deployment
[phases.release]
cmds = ["python release.py"]

[variables]
PYTHONPATH = "/app"
FLASK_APP = "main.py"
FLASK_ENV = "production"
LOG_TO_STDOUT = "1"
QT_QPA_PLATFORM = "offscreen"
OPENCV_IO_ENABLE_OPENEXR = "1"
# ALLOW_SQLITE_IN_PROD removed to prevent data loss on ephemeral filesystems
# SECRET_KEY removed from config - must be set via Railway environment variables