providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["python -m pip install --upgrade pip setuptools wheel", "python -m pip install -r requirements.txt"]

[phases.release]
dependsOn = ["install"]
cmd = "python release.py"

[start]
cmd = "gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 4 --worker-class sync --timeout 120 --keep-alive 2 --max-requests 1000 --max-requests-jitter 100"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"