[phases.setup]
nixPkgs = ["python311", "pip", "libGL", "mesa", "libglvnd-dev", "pkg-config", "libglib2.0-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --graceful-timeout 30 --threads 2 wsgi:app"

[variables]
PYTHONPATH = "/app"
LD_LIBRARY_PATH = "/nix/store"