"""Add last_sent_at to VaultInvitation for resend rate limiting

Revision ID: ad11b5287a15
Revises: 7b7f0a768b90
Create Date: 2025-09-28 10:43:04.320502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad11b5287a15'
down_revision = '7b7f0a768b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_invitation', schema=None) as batch_op:
        batch_op.drop_column('last_sent_at')

    # ### end Alembic commands ###
