"""Add missing description and tags columns to photo table

Revision ID: 778d12c5b758
Revises: 304d3e98ef6d
Create Date: 2025-09-15 04:10:25.246033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '778d12c5b758'
down_revision = '304d3e98ef6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))
        batch_op.alter_column('original_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('mime_type')
        batch_op.drop_column('upload_source')
        batch_op.drop_column('file_path')
        batch_op.drop_column('thumbnail_path')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('upload_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('original_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('tags')
        batch_op.drop_column('description')

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
